<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="coverlet.msbuild" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Moq" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <None Update="nunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <!-- Configuración de Exclusión de Cobertura -->
  <PropertyGroup>
    <CoverletOutputFormat>cobertura,opencover</CoverletOutputFormat>
    <ExcludeByFile>**/Migrations/*.cs;**/Program.cs;**/Data/SeedData.cs;**/Resources/*.cs</ExcludeByFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TiendaDawWeb.Shared\TiendaDawWeb.Shared.csproj" />
    <ProjectReference Include="..\TiendaDawWeb.Mvc\TiendaDawWeb.Mvc.csproj" />
    <ProjectReference Include="..\TiendaDawWeb.RazorPages\TiendaDawWeb.RazorPages.csproj" />
    <ProjectReference Include="..\TiendaDawWeb.Shared.Blazor\TiendaDawWeb.Shared.Blazor.csproj" />
  </ItemGroup>

</Project>
